// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taxlppvyrtmeropdnugv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRheGxwcHZ5cnRtZXJvcGRudWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MzU0MDEsImV4cCI6MjA2MTIxMTQwMX0.DOJJniQB8UJwATsoJqRymLFfCL4Ta4nKmnYxdhOZltQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);